#!/usr/bin/env python3
"""Rebuild docs/archive.html from the dated digests in docs/archive/.

The archive page reuses HTML_CSS from content_finder so the dark theme,
fonts, and design tokens stay in sync with the homepage. Only the
archive-list-specific styles live here.
"""

from __future__ import annotations

import html
import re
import sys
from datetime import datetime
from pathlib import Path

from content_finder import HTML_CSS


DOCS = Path(__file__).parent / "docs"
ARCHIVE_DIR = DOCS / "archive"


ARCHIVE_LIST_CSS = """
.archive-intro {
  padding: 16px 20px 4px;
  font-size: 13px; color: var(--fg-mid);
}
ul.digests {
  list-style: none; padding: 0; margin: 0;
}
ul.digests li {
  border-bottom: 1px solid var(--border);
}
ul.digests a {
  display: flex; justify-content: space-between; align-items: baseline;
  gap: 1rem;
  padding: 14px 20px;
  color: var(--fg); text-decoration: none;
  transition: background 0.15s, color 0.15s;
}
ul.digests a:hover { background: var(--purple-dim); color: var(--purple); }
ul.digests .date { font-size: 15px; font-weight: 500; }
ul.digests .day  { font-size: 12px; color: var(--fg-dim); }
ul.digests .empty {
  padding: 14px 20px; color: var(--fg-dim); font-size: 14px;
}
footer {
  padding: 24px 20px; font-size: 12px; color: var(--fg-dim);
  border-top: 1px solid var(--border);
}
footer a { color: var(--fg-mid); }
"""


def render_archive_html(entries: list[tuple[datetime, str]]) -> str:
    """Render the archive index page as a single HTML string.

    Pure function: takes the list of (date, filename) entries already sorted
    in display order and returns the full document. Filesystem I/O lives in
    main().
    """
    parts: list[str] = [
        "<!doctype html>",
        '<html lang="en" data-theme="dark"><head>',
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<meta name="theme-color" content="#0a0a0d">',
        '<link rel="icon" href="data:image/svg+xml,'
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
        "<text y='.9em' font-size='90'>📡</text></svg>\">",
        '<link rel="preconnect" href="https://fonts.googleapis.com">',
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
        '<link href="https://fonts.googleapis.com/css2?'
        'family=DM+Sans:wght@300;400;500;600&'
        'family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">',
        "<title>AI Digest — Archive</title>",
        f"<style>{HTML_CSS}{ARCHIVE_LIST_CSS}</style>",
        "</head><body>",
        '<div class="page">',
        '<header class="topbar">',
        '<div class="topbar-left">',
        '<span class="topbar-title">AI Digest</span>',
        '<span class="topbar-date">Archive</span>',
        '</div>',
        '<div class="topbar-right"><a href="index.html">← latest</a></div>',
        "</header>",
        f'<div class="archive-intro">{len(entries)} archived '
        f'digest{"s" if len(entries) != 1 else ""}.</div>',
        '<ul class="digests">',
    ]
    if not entries:
        parts.append('<li><span class="empty">No archived digests yet.</span></li>')
    for d, name in entries:
        parts.append(
            f'<li><a href="archive/{html.escape(name, quote=True)}">'
            f'<span class="date">{d.strftime("%d %b %Y")}</span>'
            f'<span class="day">{d.strftime("%A")}</span>'
            f"</a></li>"
        )
    parts.extend([
        "</ul>",
        '<footer>Generated by '
        '<a href="https://github.com/raidianblaster/Content-Finder">'
        "Content Finder</a></footer>",
        "</div>",
        "</body></html>",
    ])
    return "\n".join(parts)


def _collect_entries() -> list[tuple[datetime, str]]:
    files = sorted(ARCHIVE_DIR.glob("*.html"), reverse=True)
    entries: list[tuple[datetime, str]] = []
    for f in files:
        m = re.match(r"(\d{4}-\d{2}-\d{2})", f.stem)
        if not m:
            continue
        try:
            d = datetime.strptime(m.group(1), "%Y-%m-%d")
        except ValueError:
            continue
        entries.append((d, f.name))
    return entries


def main() -> int:
    if not ARCHIVE_DIR.exists():
        print(f"[warn] {ARCHIVE_DIR} does not exist; nothing to index", file=sys.stderr)
        return 0

    entries = _collect_entries()
    out = DOCS / "archive.html"
    out.write_text(render_archive_html(entries))
    print(f"[info] wrote {out} ({len(entries)} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
