"""V2 masthead + topbar markup tests.

The V2 redesign replaces the old left-aligned topbar ("AI Digest · <date> · archive")
with a sticky topbar (brand mark + nav) plus a masthead block (dateline, kicker,
compact title, meta row).  The compact + prominent configuration is the locked state:
- dateline leads the masthead with a day-of-week chip + full date
- subtitle is not rendered
- inline meta-date is not rendered (date lives in the dateline only)

These tests pin the visible markup contract — change them only when the design
spec itself changes.
"""
from __future__ import annotations

import re
from datetime import date, datetime, timezone

import content_finder as cf


def _items(n: int = 3, *, sources: list[str] | None = None) -> list[cf.Item]:
    sources = sources or ["NYT", "Techmeme", "Simon Willison"]
    out = []
    for i in range(n):
        out.append(cf.Item(
            title=f"Story {i}",
            url=f"https://example.com/s{i}",
            source=sources[i % len(sources)],
            published=datetime(2026, 5, 26, 12, 0, tzinfo=timezone.utc),
            summary="A short summary of what happened. " * 5,
        ))
    return out


# ---------------------------------------------------------------------------
# Topbar — brand mark + nav
# ---------------------------------------------------------------------------

def test_topbar_has_cf_brand_mark():
    out = cf.render_html(_items(3), top_n=3, page_date=date(2026, 5, 26))
    assert '<header class="topbar">' in out
    # Brand mark is the amber "CF" lettermark per the V2 spec
    assert re.search(r'<div class="brand-mark">\s*CF\s*</div>', out), \
        "topbar should contain the CF brand mark div"
    # Brand text label sits next to the mark
    assert "Content Finder" in out


def test_topbar_has_topnav_with_today_and_archive_links():
    out = cf.render_html(_items(3), top_n=3, page_date=date(2026, 5, 26))
    assert 'class="topnav"' in out
    # Today link is active on the today page
    assert re.search(r'<a [^>]*class="active"[^>]*>Today</a>', out) \
        or re.search(r'<a [^>]*>Today</a>[^<]*<a', out)
    assert ">Archive</a>" in out


# ---------------------------------------------------------------------------
# Masthead — kicker, title, subtitle, meta row
# ---------------------------------------------------------------------------

def test_masthead_kicker_shows_ai_digest_with_issue_number():
    out = cf.render_html(
        _items(3),
        top_n=3,
        page_date=date(2026, 5, 26),
        issue_number=142,
    )
    # Kicker block exists with the amber dot and label
    assert '<div class="kicker">' in out
    assert '<span class="dot"></span>' in out
    # Label includes both "AI Digest" and the explicit issue number
    assert "AI Digest" in out
    assert "Issue 142" in out


def test_masthead_title_has_accent_span_on_last_word():
    out = cf.render_html(_items(3), top_n=3, page_date=date(2026, 5, 26))
    # H1 with the V2 class and the amber accent span wrapping "today."
    assert '<h1 class="mast-title">' in out
    assert re.search(r'<span class="accent">today\.</span>', out), \
        "masthead title should end with <span class=\"accent\">today.</span>"


def test_masthead_subtitle_not_rendered():
    # Compact config hides the subtitle; it should not appear in the markup at all.
    out = cf.render_html(_items(3), top_n=3, page_date=date(2026, 5, 26))
    assert '<p class="mast-sub">' not in out


def test_masthead_dateline_shows_day_chip_and_full_date():
    out = cf.render_html(_items(3), top_n=3, page_date=date(2026, 5, 26))
    # Dateline container
    assert '<div class="mast-dateline">' in out
    # Day-of-week chip (text is "Tue"; CSS uppercases it)
    assert '<span class="mast-dateline-day">Tue</span>' in out
    # Full date without the day name
    assert '<span class="mast-dateline-date">26 May 2026</span>' in out


def test_masthead_meta_row_shows_items_sources_and_read_time_no_inline_date():
    items = _items(7, sources=["NYT", "Techmeme", "Simon Willison",
                                "The Verge", "Stratechery", "Bloomberg", "Reuters"])
    out = cf.render_html(items, top_n=7, page_date=date(2026, 5, 26))
    assert '<div class="mast-meta">' in out
    # Date lives in the dateline only — not duplicated inside mast-meta
    assert 'class="mast-meta-date"' not in out
    # Items count
    assert "7 items" in out
    # Distinct sources count (all 7 unique here)
    assert "7 sources" in out
    # Read-time pill
    assert re.search(r'<span class="pill">[^<]*min read</span>', out)


# ---------------------------------------------------------------------------
# Footer — V2 copy
# ---------------------------------------------------------------------------

def test_footer_uses_v2_generated_by_copy():
    out = cf.render_html(_items(3), top_n=3, page_date=date(2026, 5, 26))
    # Footer mentions Content Finder + the date (lighter copy than before)
    assert "Generated by" in out
    assert "Content Finder" in out
